### ISSUE TITLE
1003.c部分代码不理解

### ISSUE THREAD

**Issue by Larry2019** [OliverLew/PAT#18]
```
        /* read the rest of the line */
        if(c != '\n')
            while(getchar() != '\n');

```
不加这段代码会有两个点通不过，不理解这部分代码的作用？

**Comment by OliverLew** [comment]
因为在20行
https://github.com/OliverLew/PAT/blob/4ae61bab4a0a4a879da09f196226b0b6be054b6e/PATBasic/1003.c#L19-L21
如果出现不是`PAT`中的任何一个字母，就立即跳出循环了，这一行剩下的内容还在输入流中，你所问的代码就是用来清理剩下的内容。

**Comment by Larry2019** [comment]
谢谢解答，按照你的理解可以把上述代码修改，好像更容易理解。你觉得呢？
`#include <stdio.h>

int main()
{
    char c;
    int num;
    scanf("%d", &num);
    while(getchar() != '\n');  /* read the rest of the line,make sure to start from a new line later吸收回车 */
    for(int i = 0; i < num; i++)
    {
        /* pos: indicate the position of current index for count[]     */
        /* count[3]: number of As; before P, between P & T and after T */
        int pos = 0, count[3] = {0, 0, 0};
        while((c = getchar()) != '\n')
        {
            if(c == 'A')                  count[pos]++; /* count 'A's     */
            else if(c == 'P' && pos == 0) pos = 1;      /* one P before T */
            else if(c == 'T' && pos == 1) pos = 2;      /* one T after P  */
            else                          break;        /* 'wrong' string */
        }

        if(c != '\n')
            while(getchar() != '\n');//wrong string输入下，确保一次输入结束，并吸收换行符
        if(c == '\n'                        /* 1. no other characters at end */
        && pos == 2                         /* 2. appearance of 'P' and 'T'  */
        && count[1]                         /* 3. existance of 'A'           */
        && count[2] == count[1] * count[0]) /* 4. relation between numbers   */
            puts("YES");
        else
            puts("NO");

    }

    return 0;
}`

**Comment by OliverLew** [comment]
把读操作放在一起，确实可能更直观一些，我最开始是将这句while放在break前面的，其实都大同小异，或许我应该把代码内的注释写的更清楚点
