### ISSUE TITLE
1009.c改进意见

### ISSUE THREAD

**Issue by Larry2019** [OliverLew/PAT#19]
`#include <stdio.h>
#include <string.h>//gets函数
 
int main()
{
	int i, k;
	char *p,str[81];
	gets(str);
	k = strlen(str);
	p = str + k-1;
	while (p>=str)
	{
		if (*p == ' ' && *(p+1) != ' ')
		{
			*p = '\0';
			printf("%s ", p+1);
		}
        if(p==str)
             printf("%s",p);
             
		p--;
	}
	return 0;
}`
可能用指针方式更好理解

**Comment by OliverLew** [comment]
嗯，你的思路更加简单易懂，谢谢。

我将你的代码按照我自己的风格修改了一下，贴在下面，我会考虑更新我之前的代码。
```c
#include <stdio.h>
#include <string.h>

int main()
{
    char s[81], *p;

    gets(s);

    for(p = s + strlen(s) - 1; p >= s; p--)
    {
        if(*p == ' ' && *(p + 1) != ' ')
        {
            *p = '\0';
            printf("%s ", p + 1);
        }
        if(p == s)
            printf("%s", p);
    }

    return 0;
}
```

P.S. markdown插入代码段是下面这样，``只是行内代码

    ```c
    code
    ```
