### ISSUE TITLE
乙级1052.数组下标错误

### ISSUE THREAD

**Issue by AC-KID** [OliverLew/PAT#3]
https://github.com/OliverLew/PAT/blob/ceda48cc3713d4fb77df707257034e9130af7b6d/PATBasic/1052.c#L53-L57
m[0]<=10重复了5次，我想应该是m[0]……m[4]<=0

**Comment by OliverLew** [comment]
马虎了，谢谢指出。奇怪的是测试点没有检测出来。。。
