### ISSUE TITLE
1010代码提交，部分正确

### ISSUE THREAD

**Issue by mexbo** [OliverLew/PAT#5]
1010题有点小问题，提交只是部分正确

**Comment by mexbo** [comment]
指数为0的时候，好像是没有输出的

**Comment by mexbo** [comment]
感觉逻辑不对，假如说只有输入 5 0 ，你的代码是没有输出的

**Comment by OliverLew** [comment]
@mexbo 经验证，确实通过不了了。但是当时应该是通过的啊，我每次push都会检查的

不过，我代码里用的是
```c
while(scanf("%d %d", &coef, &index) != EOF) 
```
来判断输入结束，就是说不能判断回车，只能通过输入流/文件的结束来判断。测试的时候可以使用输入文件，或者使用Ctrl+D来结束输入。如果这个地方出问题的话我怀疑是PAT的测试设置有变化

**Comment by mexbo** [comment]
可能吧

**Comment by OliverLew** [comment]
找到问题了，之前这样的输出方法
```c
printf("%c%d %d", count++ ? ' ' : '\0', coef * index, index - 1);
```
是可以通过的，但是现在可能这个`\0`的输出会造成问题。

具体原因我还不明白，输出的内容看起来是不会影响的，以后恐怕不能这么写了
