### ISSUE TITLE
1052. 卖个萌 (20)

### ISSUE THREAD

**Issue by wizard26** [OliverLew/PAT#9]
测试点最后一直出错
看了你的发现应该describe三维数组大小问题
为什么column要申明为**5** ( ? _ ? )(题目说最多四个字符。。。)
```C
char symbol[3][10][4]; // wrong
```

**Comment by OliverLew** [comment]
@wizard26 C语言字符串结尾需要`\0`字符来标识结束位置，这是唯一判断字符串结束的方法，所以需要多一个字符来存储。

进一步说明，如果没有这个`\0`，C语言在例如输出这样的操作时，会向后继续读取内存内容，直到遇到一个`\0`。这些内存就超出数组之外，我们不知道具体内容是什么，这就是所谓的溢出overflow，是很危险的。

**Comment by wizard26** [comment]
懂了:P  非常感谢！
